import SideNav from '@/app/ui/sidenav'
import '@/app/ui/global.css'

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex h-screen flex-col md:flex-row md:overflow-hidden">
        <div className="w-full flex-none md:w-64">
          <SideNav />
        </div>
        <section className="flex flex-grow p-4 md:overflow-y-auto">
          {children}
        </section>
      </body>
    </html>
  )
}
